CREATE TABLE users (
    -- id INTEGER PRIMARY KEY AUTOINCREMENT,
    mail VARCHAR NOT NULL PRIMARY KEY,
    password VARCHAR NOT NULL
);

CREATE TABLE offers (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    owner VARCHAR NOT NULL,
    type VARCHAR NOT NULL,
    description TEXT NOT NULL,
    price REAL NOT NULL,
    date_amount INTEGER NOT NULL,
    FOREIGN KEY(owner) REFERENCES users(mail)
);

CREATE TABLE transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    offer_id INTEGER NOT NULL,
    buyer VARCHAR NOT NULL,
    amount INTEGER,
    bid REAL,
    FOREIGN KEY(offer_id) REFERENCES offers(id),
    FOREIGN KEY(buyer) REFERENCES users(mail)
)