CREATE TABLE users (
    -- id INTEGER PRIMARY KEY AUTOINCREMENT,
    mail VARCHAR NOT NULL PRIMARY KEY,
    password VARCHAR NOT NULL
);

CREATE TABLE offers (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    type VARCHAR NOT NULL,
    description TEXT NOT NULL,
    price REAL NOT NULL,
    date_amount INTEGER NOT NULL
);

CREATE TABLE owners (
    mail VARCHAR NOT NULL,
    id INTEGER NOT NULL,
    PRIMARY KEY (mail, id)
)