# Generated by Django 2.1.4 on 2019-01-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('auction', 'auction'), ('buynow', 'buynow')], max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AuctionOffer',
            fields=[
                ('offer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offers.Offer')),
                ('date', models.BigIntegerField()),
                ('status', models.CharField(choices=[('active', 'active'), ('expired', 'expired')], max_length=10)),
                ('last_bid', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('offers.offer',),
        ),
        migrations.CreateModel(
            name='BuyNowOffer',
            fields=[
                ('offer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='offers.Offer')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount', models.BigIntegerField()),
            ],
            bases=('offers.offer',),
        ),
    ]
